services:
  - type: web
    name: pdf-parser-service
    env: python
    buildCommand: |
     pip install -r requirements.txt
     python -m playwright install
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    autoDeploy: true
    plan: free