services:
  - type: web
    name: pdf-parser-service
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
      playwright install-deps chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/ms-playwright"